### ISSUE TITLE
Classifier updates

### ISSUE THREAD

**Issue by marcverhagen** [tarsqi/ttk#17]
Checklist of things to be done for the classifier:
- [x] Add a Mallet interface
- [x] Map old TimeBank 1.2, with instances, to new version using new TimeML specs and the TTK format
- [x] Run preprocessor on new TimeBank so we have all the features needed by classifier
- [x] create vectors from pre-processed TimeBank
- [x] Create a Mallet model from TimeBank
- [x] Create vectors that can be used by Mallet
- [x] Fix the obvious mistakes in the features in vectors.py
- [ ] Need to add more features
- [x] Add a Tarsqi option to determine what trainer to use
- [x] See if we can get rid of the temporary files
- [ ] The above was done but needs a bit more testing before it can replace the file based processing
- [x] Make sure this works with the most recent Mallet download, for example, we may have changed things in the mallet shell

**Comment by ajaygupta123** [comment]
Any input on how to create our own classifier with new set of features?

**Comment by marcverhagen** [comment]
@ajaygupta123 
Clearly I did not check the issues very well for a while. I am porting the code to Python3 and after that will replace the Mallet classifier with a scikit-learn classifier, at which point I will make it easier for users to create classifiers.

**Comment by marcverhagen** [comment]
Closing because the Mallet classifier will be phased out and replaced by an sklearn classifier.
