### ISSUE TITLE
Inline tags

### ISSUE THREAD

**Issue by mnavasloro** [tarsqi/ttk#81]
Hello,

Is there any way to force TARSQI to output inline annotation, around the annotated text, instead of in the form of a list of annotations after the text?

Thank you and best regards,

María Navas Loro

**Comment by marcverhagen** [comment]
Sorry for the late reply. But in case this is still useful...

You cannot force TARSQI to create inline tags. However, you can use the utilities/convert.py script to  take the standard TARSQI output and create HTML.
